version: '2'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        env_file:
            - variables.dev.env
        volumes:
            - .:/app/
        ports:
            - "4000:3000"
        depends_on:
            - mysql-db
        networks:
            - app
            - datastore
        tty: true
        stdin_open: true
    mysql-db:
        image: mysql:5.7
        container_name: 'mysql-db'
        environment:
            - TZ=JST-9
            - MYSQL_ROOT_PASSWORD=hito
        privileged: true
        networks:
            - datastore
        ports:
            - "3315:3306"
networks:
    app:
    datastore:
